    SELECT p.PRODUCT_CODE,p.PRICE * SUM(o.SALES_AMOUNT) as SALES
    FROM product as p, offline_sale as o
    WHERE p.PRODUCT_ID = o.PRODUCT_ID
    GROUP BY p.PRODUCT_CODE
    ORDER BY SALES DESC, p.PRODUCT_CODE ASC